### ISSUE TITLE
テーブルコンポーネントのヘッダーがクリック可能になっている

### ISSUE THREAD

**Issue by yutaro-elk** [CauchyE/telescope#219]
|バージョン| 
|-|
|v0.0.71| 

## 概要
テーブルコンポーネントのヘッダーがクリック可能になっている。

![Kapture 2021-11-19 at 15 14 30](https://user-images.githubusercontent.com/36399275/142574491-b2fca1fd-499a-4f2f-8a30-2cb4e86e13f0.gif)

## 再現方法
1. Txs ページに遷移
2. 「Block Height」をクリック

## 期待値
クリックエフェクトがでないようにする

**Comment by YasunoriMATSUOKA** [comment]
修正完了を確認したのでクローズしておきます。
