### ISSUE TITLE
simulate txのcosmos clientへの逆輸入

### ISSUE THREAD

**Issue by KimuraYu45z** [CauchyE/telescope#259]
https://github.com/CauchyE/telescope/blob/main/projects/main/src/app/models/cosmos/tx-common.model.ts
これはcosmos clientがもったほうが人類ハッピーな気がしています

**Comment by YasunoriMATSUOKA** [comment]
@KimuraYu45z 
型をcosmos-clientで持つという点については、特に異論なく、便利になって良いと思いました。(プロパティ名はちょっと考えたほうがいいかもしれません。特にminimumGasPriceは、ノード上の設定値としては、確かにその名前なのですが、クライアントサイドから見るとちょっと違和感がある名前かもしれないなあ等、改めて見て思いました。)

レスポンスの値まで含めて渡せるようなメソッドを追加するような想定の場合は、現時点でのtelescope内部の実装だと、余裕率1.1倍のハードコードされていますが、そこを調整できるようにしておいたほうが良いかもしれない等は思いました。

**Comment by KimuraYu45z** [comment]
これ、いろいろ考えた結果やはりやめることにします。
https://github.com/CauchyE/telescope/blob/main/projects/main/src/app/models/cosmos/tx-common.model.ts
の型がcosmos のapiの仕様に制約されたなんらかの型だと思ってたけどそうではないっぽいのに気づいたので。。
